version: '3.8'

services:
  cd-server:
    build:
      context: ./cd-server
    container_name: cd-server
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - app-network
    volumes:
      - cd-server-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"] 
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  db:
    image: "postgres:latest"
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ci_cd_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tester:
    build:
      context: ./tester
    container_name: tester
    depends_on:
      cd-server:
          condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./tests:/app/tests

networks:
  app-network:
    driver: bridge

volumes:
  cd-server-data:
  redis-data:
  postgres-data:
